name: Cleanup Action Caches

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clean-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Get caches list
        id: list-caches
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/caches")
          echo "$response" | jq -r '.actions_caches | sort_by(.created_at) | reverse' > caches.json

      - name: Delete old caches
        run: |
          latest_cache_id=$(jq -r '.[0].id' caches.json)
          jq -c '.[1:] | .[]' caches.json | while read -r cache; do
            cache_id=$(echo $cache | jq -r '.id')
            curl -X DELETE -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/caches/$cache_id"
          done
        if: success()
      
      - name: Clean up
        run: rm -f caches.json